---
- name: Ensure rpcbind and nfslock are running.
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - rpcbind
    - nfslock

- name: Ensure nfs is running.
  service: "name=nfs state=started enabled=yes"
  when: (ansible_distribution != "Fedora"
          and ansible_distribution_major_version|int <=6)
        or (ansible_distribution == "Fedora"
          and ansible_distribution_major_version|int <= 15)

# "service name=nfs enabled=yes" fails on RHEL 7
# because of weird symlink handling in systemd - we have to use nfs-server.
- name: Ensure nfs-server and nfs-secure is running.
  service: "name=nfs-server state=started enabled=yes"
  when: (ansible_distribution != "Fedora"
          and ansible_distribution_major_version|int >= 7)
        or (ansible_distribution == "Fedora"
          and ansible_distribution_major_version|int >= 16)
